version: '3.8'

networks:
  ca-network:
    driver: bridge

volumes:
  cadb-data:
    driver: local
  caprovidence-media:
    driver: local
  caelastic-data:
    driver: local

services:
  caprovidence:
    build:
      context: .
      dockerfile: ./.docker/providence/Dockerfile
    container_name: caprovidence
    image: caprovidence
    volumes:
      - ./apps/providence/setup.php:/var/www/html/providence/setup.php
      - ./apps/providence/app/conf/local:/var/www/html/providence/app/conf/local
      - caprovidence-media:/var/www/html/providence/media
      - ./apps/pawtucket/setup.php:/var/www/html/setup.php
    ports:
      - "80:80"
    depends_on:
      - cadb
      - caelastic
    networks:
      - ca-network

  cadb:
    container_name: cadb
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "ca_user"
      MYSQL_PASSWORD: "ca_password"
      MYSQL_DATABASE: "ca"
    volumes:
      - cadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - ca-network

  caelastic:
    container_name: caelastic
    # image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    # image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    # image: elasticsearch:8.2.2
    image: elasticsearch:5.6.16
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      # - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    #   nofile:
    #     soft: 262144
    #     hard: 262144
    # mem_limit: 1g
    # cap_add:
    #   - IPC_LOCK
    volumes:
      - caelastic-data:/usr/share/elasticsearch/data
      - ./.docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - ca-network
