#!/bin/bash
set -e

# #DATABASE INIT/CONFIG
mysql -h $MYSQL8_1_PORT_3306_TCP_ADDR -uroot -p$MYSQL8_1_ENV_MYSQL_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;" --ssl-mode=DISABLED
mysql -h $MYSQL8_1_PORT_3306_TCP_ADDR -uroot -p$MYSQL8_1_ENV_MYSQL_ROOT_PASSWORD -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER';" --ssl-mode=DISABLED